language: java
jdk:
  - openjdk7

branches:
  only:
    - master
    - develop
    - /^(?i:release).*$/
    - /^(?i:support).*$/
    - /^(?i:hotfix)-.*$/

install: ./gradlew setupCIWorkspace -S
script: ./gradlew build curse

env:
  global:
    TERM=dumb
